Fix issue #1388: broken model-only relationships
propelorm/Propel2 pull request #1389
Opened 2017-06-12 13:29 UTC by AlexanderBliznuk

2017-06-12 13:30 UTC, marcj commented on tests/Propel/Tests/Issues/Issue1388Test.php
> +        $this->assertTrue($noExceptionThrown);
When a exception is thrown this test is automatically marked as failed, so no need for that assertTrue :)

2017-07-07 15:20 UTC, marcj requested changes

2017-07-07 15:20 UTC, marcj commented on src/Propel/Generator/Model/Table.php
> +                    if (!$foreignPrimaryKey->hasReferrer($foreignKey) && !$foreignKey->isSkipSql() && $throwErrors) {
well, generating SQL has nothing to do with checking for valid foreign keys. So this check is a misuse of the `skip-sql` attribute to allow models generation with invalid foreign keys.

2017-08-14 20:20 UTC, AlexanderBliznuk commented on src/Propel/Generator/Model/Table.php
> +                    if (!$foreignPrimaryKey->hasReferrer($foreignKey) && !$foreignKey->isSkipSql() && $throwErrors) {
Propel used to allow flexible models tailored for application's needs. This checking for foreign keys merely ties hands. For example, if referent table has composite key, it appears to be impossible to join it by a column outside the key.
Please also consider fully justified and common scenario: i18n tables having primary key(id, locale). Of course in many cases other tables would refer to i18n tables only by id. Another similar common scenario is versioning of entities. 
Maybe it's ok to be strict and thus guarantee scheme validity between different RDBMS and to guide amateurs.
But  [model only relationships](http://propelorm.org/documentation/04-relationships.html#model-only-relationships) feature shouldn't be broken. It doesn't work now as described in docs and my pull request fixes this regression.

2026-06-30 08:07 UTC, gechetspr commented
We are conducting a cleanup. If you think that this PR is still valid, please re-open PR and we will check it

2026-06-30 08:07 UTC, closed without merging