add howto url to missing loader script exception
propelorm/Propel2 pull request #1757
Opened 2021-06-21 13:33 UTC by mringler

In order to reduce confusion and resulting bug reports about an outdated configuration or missing database import, I have created a howto page in the Propel2 wiki at https://github.com/propelorm/Propel2/wiki/Loading-the-database, and I have added the URL to the exception message.

I am not sure if the wiki is the correct location, but I am not sure if the official documentation is still maintained, so the wiki seems like the next best thing. Please let me know if the howto should go somewhere else.

2021-06-21 13:52 UTC, dereuromark approved these changes
Given, that we want to start stabilizing the (beta) 2.0 release, we should now make a release that cleans up a lot.
This seems helpful to get there.

2021-06-22 12:00 UTC, gechetspr requested changes
visibility of constant can definitely be protected, but the rest of changes are not mandatory

2021-06-22 12:36 UTC, dereuromark commented on src/Propel/Runtime/ServiceContainer/StandardServiceContainer.php
> +            $message .= sprintf(' Visist %s for information on how to fix this.', self::HOWTO_FIX_MISSING_LOADER_SCRIPT_URL);
```suggestion
            $message .= sprintf(' Visit %s for information on how to fix this.', self::HOWTO_FIX_MISSING_LOADER_SCRIPT_URL);
```

2021-06-22 12:36 UTC, dereuromark commented on src/Propel/Runtime/ServiceContainer/StandardServiceContainer.php
> +                . 'Visist %s for information on how to fix this.';
Same here

2021-06-22 12:40 UTC, mringler commented
@gechetspr Thank you for the review. I updated the code as you requested.
@dereuromark Thanks for finding the typo

First CI run after push failed, when the connection to the database could not be established (see [here](https://github.com/propelorm/Propel2/pull/1757/checks?check_run_id=2884657122)). Currently, this happens every other time I push a commit.

2021-06-22 12:44 UTC, merged