Fix up typos.
propelorm/Propel2 pull request #1806
Opened 2021-12-06 14:10 UTC by dereuromark

Time to fix some typos for the next beta release.

We wil have to note the small BC topic in the changelogs:
- public function setSlowThreshold($slowThreshold)

2021-12-06 21:08 UTC, mringler approved these changes

2021-12-07 08:48 UTC, a-sabaa requested changes

2021-12-07 08:48 UTC, a-sabaa commented on src/Propel/Generator/Command/AbstractCommand.php
> +     * Parses a connection string and returns an array with name, DNS and extra information.
I don't think this is DNS, it's actually DSN (data source name).

2021-12-07 14:27 UTC, a-sabaa approved these changes

2021-12-07 14:35 UTC, merged